// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeBinlog(arg1:main.AnalyzeRequest):Promise<void>;

export function ExportSQL(arg1:Record<string, any>,arg2:string):Promise<string>;

export function GetTables(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function ParseBinlogStatus(arg1:string):Promise<Array<main.BinlogResult>>;

export function SelectFolder():Promise<string>;

export function StopAnalyze():Promise<void>;

export function TestConnection(arg1:string):Promise<Array<string>>;
