// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeBinlog(arg1) {
  return window['go']['main']['App']['AnalyzeBinlog'](arg1);
}

export function ExportSQL(arg1, arg2) {
  return window['go']['main']['App']['ExportSQL'](arg1, arg2);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function ParseBinlogStatus(arg1) {
  return window['go']['main']['App']['ParseBinlogStatus'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StopAnalyze() {
  return window['go']['main']['App']['StopAnalyze']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
